name: NPMJS prod publishing

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run checks
      - run: npm run publish:prod
        if: github.event.pull_request.merged
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
